responder_pergunta_compliance:
  description:
    Responder perguntas voltadas à matemática, álgebra e cálculo com base nos documentos fornecidos 
    pelo ICMC-USP, seguir e fornecer informações de forma clara, seguindo notação.

    Pergunta:{pergunta}

  expected_output:
    Uma resposta de fácil compreensão, estruturada e fundamentada nos documentos PDF disponibilizados.
    Quando necessário, utilizar LaTeX para expressar fórmulas matemáticas, gráficos ou outras representações visuais.

  agent: especialista_compliance